Repository MazeSolvers/MazeSolver_front, pull requests merged in 2024-07, with the labels that each got.

#1 feat: threejs view를 위한 기본 설정
  css/style.css
  index.html
  js/controls.js
  js/game.js
  js/main.js
Labels: good first issue

#9 Map 구현
  js/game.js
  js/main.js
  js/mazeGenerator.js
  js/npc.js
  js/player.js
  js/wallcreator.js
Labels: enhancement

#10 feat: 미로 행렬화
  js/checkmaze.js
  js/game.js
  js/mazeGenerator.js
  js/wallcreator.js
Labels: enhancement

#11 feat: 초기 미로 생성 및 npc 무빙 수정
  index.html
  js/game.js
  js/npc.js
Labels: enhancement

#16 feat: 나침반 구현
  .vscode/launch.json
  index.html
  js/compass.js
  js/game.js
  js/player.js
Labels: enhancement

#17 Dfs를 이용하여 경로 보장 알고리즘 구현
  js/checkmaze.js
  js/game.js
  js/npc.js
  js/wallcreator.js
Labels: enhancement

#25 멀티플레이를 위한 golang 기본 서버 기능 강화
  js/game.js
  server/checkmaze.go
  server/main.go
Labels: documentation

#24 feat: 기본 미로 생성
  js/game.js
  js/mazeGenerator.js
Labels: enhancement
